ticket/DM-29917: Added the infrastructure for the IntegrationTests Conda package.
lsst-ts/ts_jenkins_shared_library pull request #26
Opened 2021-05-07 17:22 UTC by rbovill

2021-05-07 21:23 UTC, mareuter requested changes
A few suggestions to cut down on some of the hard coding.

2021-05-07 21:23 UTC, mareuter commented on vars/IntTestsPipeline.groovy
> +                    recipients: "rbovill@lsst.org",
There looks to be a function on Csc (Csc.email()) that looks to return a dictionary like object that could then be used to assign the correct email via the package name. We should leverage that here.

2021-05-07 21:23 UTC, mareuter commented on vars/IntTestsPipeline.groovy
> +                    def userId = "U2NF4GWV8"
There looks to be a function on Csc (Csc.slack_id()) that looks to return a dictionary like object that could then be used to assign the correct Slack ID via the package name. We should leverage that here.

2021-05-07 21:23 UTC, mareuter commented on vars/IntTestsPipeline.groovy
> +                    def userId = "U2NF4GWV8"
Ditto from above.

2021-05-07 21:23 UTC, mareuter commented on vars/IntTestsPipeline.groovy
> +                                csc.upload_conda("ts-integrationtests","main","linux-64")
Should make ts-integrationtests a local variable since it is used more than once. Will also help with the comments about email and Slack ID.

2021-05-10 19:20 UTC, rbovill commented on vars/IntTestsPipeline.groovy
> +                    recipients: "rbovill@lsst.org",
Fixed

2021-05-10 19:20 UTC, rbovill commented on vars/IntTestsPipeline.groovy
> +                    def userId = "U2NF4GWV8"
Fixed

2021-05-10 19:20 UTC, rbovill commented on vars/IntTestsPipeline.groovy
> +                    def userId = "U2NF4GWV8"
Fixed

2021-05-10 19:20 UTC, rbovill commented on vars/IntTestsPipeline.groovy
> +                                csc.upload_conda("ts-integrationtests","main","linux-64")
Fixed

2021-05-10 19:42 UTC, mareuter approved these changes
Thank you for the changes. Looks  good.

2021-05-10 21:21 UTC, merged