tickets/DM 38375
lsst-ts/ts_jenkins_shared_library pull request #97
Opened 2023-03-17 19:00 UTC by couger01

- Remove branch argument
- Use named parameters in map

2023-03-18 21:23 UTC, r-owen approved these changes
Thank you for this useful change. I don't know enough Groovy to do a thorough review, so my apologies if I missed anything.

2023-03-20 12:59 UTC, wvreeven requested changes
Please make sure that the job fails if the two mandatory arguments are missing from the map.

2023-03-20 12:59 UTC, wvreeven commented on vars/DevelopPipeline.groovy
> +    idl_string = "${pipeline_args.idl_name} "
What happens if the `idl_name` arg is missing from the map? I think the job should be marked as failed with an error message indicating that that parameter is mandatory. Same for `module_name`.

2023-03-20 15:24 UTC, wvreeven approved these changes
Looks good to me.

2023-03-20 15:24 UTC, wvreeven commented on vars/DevelopPipeline.groovy
> +        error "Need to define name, idl_name or module_name."
`or` -> `and`

2023-03-20 15:49 UTC, merged